version: "3"
services:
    app:
        image: thecodingmachine/php:8.1-v4-apache
        volumes:
            - ../:/var/www/html
        environment:
            APACHE_DOCUMENT_ROOT: 'somewhere/'
            VIRTUAL_HOST: 'www.awesome.com'
            CERT_NAME: dev
        networks:
            - 'proxy_network'
        hostname: awesome_app
networks:
    proxy_network:
        external: true
